<?php
/**
 * @var $block \Behindshops\Customerstatus\Block\Status
 */

?>
<?php if ($this->isLoggedIn()):?>
<li><a  href="<?= $this->getStatusUrl() ?>">
        <?php if ($this->getStatus()):?>
            <span style='color: #2ca02c;'><?= $block->escapeHtml(__('Is enabled'))?></span>
        <?php else: ?>
            <span style='color:#fdf0d5;'><?=$block->escapeHtml(__('Is disabled'))?></span>
        <?php endif; ?>
     </a>
</li>
<?php endif; ?>